### ISSUE TITLE
[vue] todo 앱 만들기

### ISSUE THREAD

**Issue by kwonET** [kwonET/toyprojects#1]
- [ ] 기본 컴포넌트 및 기능 추가
- [ ] 사용자 기능 개선
- [ ] 날씨 기능 추가
- [ ] 타이머 기능 추가
